### ISSUE TITLE
Add borders to images

### ISSUE THREAD

**Issue by krzychukula** [kwasniew/hyperbook#11]
It's hard to read the content when images have the same background colour as the page. 
1. Pick a different background colour (probably for the project page)
2. Or add a border to the images. (embedded in the image to fix it even without CSS).

See the image below. Where does the `screenshot` start and where does it end?

<img width="629" alt="Zrzut ekranu 2020-06-4 o 13 13 22" src="https://user-images.githubusercontent.com/240264/83750180-33409680-a665-11ea-80dc-0f93194deaa2.png">

**Comment by kwasniew** [comment]
@krzychukula I switched to sakura.css which solves this problem. Will be updating all images soon.
